### ISSUE TITLE
Repurpose to a new name?

### ISSUE THREAD

**Issue by AraHaan** [AraHaan/dbapi#4]
I been thinking if we should rename this so that way this can go onto PyPI.

**Comment by AraHaan** [comment]
alright so @martmists any idea for an new name for this that is unique for pypi.

**Comment by AraHaan** [comment]
... github...

**Comment by Martmists-GH** [comment]
Is this really needed?

**Comment by EJH2** [comment]
2 hours and 15 emails later, please remind me why this is needed and why you decided to assign everyone

**Comment by AraHaan** [comment]
this is needed because an packafe of the same name exists in pypi however does something entirely different. So we need to rename some someone can easily pip install this from pypi without accidentally installing the package from there that currently has the same name and then they wonder whydverything is not working the way they expect because they dont see the functions this provides there.

**Comment by Martmists-GH** [comment]
We'll be putting this on hiatus for now as:

- A new website + API is being worked on
- Current implementation doesn't support:
  - The `requests` module, for synchronous bots or bots using disco
  - Other bot services such as DBL
- Not all classes are publicly accessible
- No docs released yet

Once the majority of these are fixed, we will consider putting this on pypi. Feel free to reopen this when that time is due.
